### ISSUE TITLE
DLIP-004 more friendly document for Dapp Learning

### ISSUE THREAD

**Issue by bobjiang** [Dapp-Learning-DAO/DLIP#4]
Context:
We had github repo to store many codes, but it is not friendly for new users (in special non-coder).

Proposal:
Let's build a text document for non-developer and easy to contribute.

Solution:
build document on gitbook (easily integrate with github)

here is an example:
https://docs.giveth.io/

**Comment by liberhe** [comment]
Good, so let's do this
